version: '3'

services:
  oc_client:
    image: $IMAGE:test
    container_name: oc_client_test
    restart: always
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: $VIRTUAL_HOST
      LETSENCRYPT_HOST: $LETSENCRYPT_HOST
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL

networks:
  default:
    external:
      name: frontend_default
