version: '3'

services:
  oc_client_prod:
    image: $IMAGE:prod
    container_name: oc_client_prod
    restart: always
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: $VIRTUAL_HOST
      LETSENCRYPT_HOST: $LETSENCRYPT_HOST
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL

networks:
  default:
    external:
      name: frontend_default
