version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: Deploy to stage
          command: |
            pwd
            ls -alh
            mkdir -p certs
            ls -alh
