version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: Deploy to stage
          command: |
            mkdir -p certs
            echo -e $DOCKERCA > certs/ca.pem
            echo -e $DOCKERCERT > certs/cert.pem
            echo -e $DOCKERKEY > certs/key.pem
            ls -alh certs
            cat certs/ca.pem
            export DOCKER_TLS_VERIFY="1"
            export DOCKER_HOST="tcp://$STAGEHOST:2376"
            export DOCKER_CERT_PATH="/home/circleci/project/certs"
            docker ps
